export const libraries = [
	// Languages, runtimes & systems
	"python/cpython",
	"golang/go",
	"rust-lang/rust",
	"nodejs/node",
	"denoland/deno",
	"oven-sh/bun",
	"microsoft/TypeScript",
	"dotnet/runtime",
	"bytecodealliance/wasmtime",
	"emscripten-core/emscripten",
	"SerenityOS/serenity",

	// Frontend frameworks
	"vuejs/core",
	"react/react",
	"sveltejs/svelte",
	"solidjs/solid",
	"angular/angular",
	"preactjs/preact",
	"emberjs/ember.js",
	"alpinejs/alpine",
	"bigskysoftware/htmx",

	// Meta-frameworks & SSR
	"nuxt/nuxt",
	"vercel/next.js",
	"withastro/astro",
	"sveltejs/kit",
	"remix-run/remix",
	"gatsbyjs/gatsby",
	"freshframework/fresh",
	"nitrojs/nitro",
	"quasarframework/quasar",

	// Vue & Nuxt ecosystem
	"vuejs/router",
	"vuejs/pinia",
	"vuejs/devtools",
	"vuejs/vitepress",
	"vuejs/language-tools",
	"vuejs/test-utils",
	"vueuse/vueuse",
	"intlify/vue-i18n",
	"nuxt/ui",
	"nuxt/content",
	"nuxt/image",
	"nuxt-modules/i18n",
	"unovue/reka-ui",
	"vuetifyjs/vuetify",
	"element-plus/element-plus",
	"tusen-ai/naive-ui",
	"unjs/unhead",
	"nuxt/fonts",
	"nuxt/test-utils",

	// UI components & design systems
	"shadcn-ui/ui",
	"radix-ui/primitives",
	"heroui-inc/heroui",
	"lucide-icons/lucide",
	"chakra-ui/chakra-ui",
	"mantinedev/mantine",
	"ant-design/ant-design",
	"arco-design/arco-design",
	"storybookjs/storybook",

	// CSS & styling
	"tailwindlabs/tailwindcss",
	"unocss/unocss",
	"postcss/postcss",
	"sass/dart-sass",
	"cssnano/cssnano",

	// State management & data fetching
	"TanStack/query",
	"TanStack/table",
	"TanStack/router",
	"react-hook-form/react-hook-form",
	"reduxjs/redux",
	"reduxjs/redux-toolkit",
	"mobxjs/mobx",
	"pmndrs/zustand",
	"pmndrs/jotai",
	"facebook/relay",
	"apollographql/apollo-client",
	"vercel/swr",

	// Build tools & bundlers
	"vitejs/vite",
	"rolldown/rolldown",
	"webpack/webpack",
	"rollup/rollup",
	"evanw/esbuild",
	"swc-project/swc",
	"babel/babel",
	"web-infra-dev/rspack",
	"parcel-bundler/parcel",
	"oxc-project/oxc",
	"privatenumber/tsx",
	"rolldown/tsdown",

	// Linting, formatting & monorepo tooling
	"biomejs/biome",
	"eslint/eslint",
	"typescript-eslint/typescript-eslint",
	"antfu/eslint-config",
	"prettier/prettier",
	"webpro-nl/knip",
	"astral-sh/ruff",
	"python/mypy",
	"nrwl/nx",
	"vercel/turborepo",
	"changesets/changesets",
	"moonrepo/moon",

	// Package & version managers
	"pnpm/pnpm",
	"npm/cli",
	"yarnpkg/berry",
	"npmx-dev/npmx.dev",
	"jdx/mise",
	"Schniz/fnm",
	"nvm-sh/nvm",
	"asdf-vm/asdf",
	"astral-sh/uv",
	"rust-lang/cargo",

	// Testing & browser automation
	"vitest-dev/vitest",
	"jestjs/jest",
	"pytest-dev/pytest",
	"cypress-io/cypress",
	"microsoft/playwright",
	"puppeteer/puppeteer",
	"SeleniumHQ/selenium",
	"testing-library/react-testing-library",
	"wiremock/wiremock",
	"grafana/k6",

	// Backend frameworks
	"expressjs/express",
	"fastify/fastify",
	"koajs/koa",
	"micronaut-projects/micronaut-core",
	"adonisjs/core",
	"feathersjs/feathers",
	"honojs/hono",
	"elysiajs/elysia",
	"nestjs/nest",
	"loopbackio/loopback-next",
	"fastapi/fastapi",
	"h3js/h3",
	"django/django",
	"pallets/flask",
	"rails/rails",
	"laravel/laravel",
	"symfony/symfony",
	"spring-projects/spring-boot",
	"dotnet/aspnetcore",
	"gin-gonic/gin",
	"labstack/echo",
	"beego/beego",
	"gofiber/fiber",
	"go-chi/chi",
	"actix/actix-web",
	"tokio-rs/tokio",
	"tokio-rs/axum",
	"vapor/vapor",
	"quarkusio/quarkus",

	// APIs & networking
	"trpc/trpc",
	"socketio/socket.io",
	"axios/axios",
	"unjs/ofetch",
	"seanmonstar/reqwest",
	"n0-computer/iroh",
	"bluesky-social/atproto",

	// Utilities & validation
	"colinhacks/zod",
	"jquense/yup",
	"date-fns/date-fns",
	"serde-rs/serde",

	// Databases & data stores
	"mongodb/mongo",
	"redis/redis",
	"valkey-io/valkey",
	"MariaDB/server",
	"cockroachdb/cockroach",
	"tikv/tikv",
	"surrealdb/surrealdb",
	"yugabyte/yugabyte-db",
	"vitessio/vitess",
	"neo4j/neo4j",
	"influxdata/influxdb",
	"ClickHouse/ClickHouse",
	"duckdb/duckdb",
	"StarRocks/starrocks",
	"elastic/elasticsearch",
	"pingcap/tidb",
	"seaweedfs/seaweedfs",

	// ORMs & query builders
	"prisma/orm",
	"sequelize/sequelize",
	"typeorm/typeorm",
	"knex/knex",
	"drizzle-team/drizzle-orm",
	"Automattic/mongoose",

	// Data & streaming infrastructure
	"apache/kafka",
	"apache/pulsar",
	"apache/flink",
	"apache/spark",
	"apache/rocketmq",
	"nats-io/nats-server",
	"rabbitmq/rabbitmq-server",
	"apache/airflow",

	// Cloud native & DevOps
	"kubernetes/kubernetes",
	"kubernetes/website",
	"kubernetes-sigs/kustomize",
	"k3s-io/k3s",
	"rancher/rancher",
	"helm/helm",
	"moby/moby",
	"docker/compose",
	"containerd/containerd",
	"etcd-io/etcd",
	"istio/istio",
	"linkerd/linkerd2",
	"cilium/cilium",
	"envoyproxy/envoy",
	"traefik/traefik",
	"caddyserver/caddy",
	"argoproj/argo-cd",
	"argoproj/argo-workflows",
	"fluxcd/flux2",
	"fluxcd/flagger",
	"crossplane/crossplane",
	"rook/rook",
	"longhorn/longhorn",
	"coollabsio/coolify",

	// Infrastructure as code
	"hashicorp/terraform",
	"hashicorp/packer",
	"hashicorp/nomad",
	"hashicorp/consul",
	"pulumi/pulumi",
	"ansible/ansible",

	// Observability & analytics
	"prometheus/prometheus",
	"grafana/grafana",
	"grafana/loki",
	"grafana/tempo",
	"open-telemetry/opentelemetry-js",
	"open-telemetry/opentelemetry-collector",
	"jaegertracing/jaeger",
	"getsentry/sentry",
	"highlight/highlight",
	"PostHog/posthog",
	"umami-software/umami",
	"plausible/analytics",
	"matomo-org/matomo",
	"GoogleChrome/lighthouse",

	// Security, auth & identity
	"hashicorp/vault",
	"open-policy-agent/opa",
	"falcosecurity/falco",
	"aquasecurity/trivy",
	"projectdiscovery/nuclei",
	"data-privacy-stack/presidio",
	"goauthentik/authentik",
	"authelia/authelia",
	"zitadel/zitadel",
	"keycloak/keycloak",
	"ory/kratos",
	"supertokens/supertokens-core",
	"bitwarden/server",
	"dani-garcia/vaultwarden",

	// AI/ML frameworks & training
	"pytorch/pytorch",
	"tensorflow/tensorflow",
	"keras-team/keras",
	"scikit-learn/scikit-learn",
	"huggingface/transformers",
	"huggingface/accelerate",
	"huggingface/peft",
	"huggingface/tokenizers",
	"huggingface/datasets",
	"huggingface/diffusers",
	"deepspeedai/DeepSpeed",

	// LLM serving & inference
	"ollama/ollama",
	"ggml-org/llama.cpp",
	"vllm-project/vllm",
	"sgl-project/sglang",
	"BerriAI/litellm",

	// LLM apps & agent frameworks
	"langchain-ai/langchain",
	"langchain-ai/langgraph",
	"run-llama/llama_index",
	"langgenius/dify",
	"microsoft/autogen",
	"crewAIInc/crewAI",
	"microsoft/semantic-kernel",
	"guidance-ai/guidance",
	"browser-use/browser-use",
	"getzep/graphiti",
	"mem0ai/mem0",
	"anthropics/skills",
	"openclaw/openclaw",
	"lobehub/lobehub",
	"open-webui/open-webui",
	"continuedev/continue",
	"khoj-ai/khoj",
	"onyx-dot-app/onyx",

	// Vector databases & retrieval
	"chroma-core/chroma",
	"qdrant/qdrant",
	"milvus-io/milvus",
	"weaviate/weaviate",
	"pgvector/pgvector",

	// Speech, audio & generative media
	"openai/whisper",
	"ggml-org/whisper.cpp",
	"modelscope/FunASR",
	"espnet/espnet",
	"Comfy-Org/ComfyUI",
	"AUTOMATIC1111/stable-diffusion-webui",
	"invoke-ai/InvokeAI",
	"vladmandic/sdnext",
	"LibreTranslate/LibreTranslate",

	// Data science & notebooks
	"pandas-dev/pandas",
	"numpy/numpy",
	"scipy/scipy",
	"matplotlib/matplotlib",
	"jupyterlab/jupyterlab",
	"pola-rs/polars",
	"gradio-app/gradio",
	"streamlit/streamlit",

	// Graphics, 3D & visualization
	"mrdoob/three.js",
	"pixijs/pixijs",
	"BabylonJS/Babylon.js",
	"playcanvas/engine",
	"pmndrs/react-three-fiber",
	"pmndrs/drei",
	"CesiumGS/cesium",
	"plotly/plotly.js",
	"chartjs/Chart.js",
	"processing/p5.js",
	"remotion-dev/remotion",
	"excalidraw/excalidraw",
	"tldraw/tldraw",

	// Game engines & games
	"godotengine/godot",
	"bevyengine/bevy",
	"libgdx/libgdx",
	"phaserjs/phaser",
	"yairm210/Unciv",

	// Desktop & mobile
	"flutter/flutter",
	"react/react-native",
	"expo/expo",
	"ionic-team/ionic-framework",
	"ionic-team/capacitor",
	"electron/electron",
	"tauri-apps/tauri",
	"NativeScript/NativeScript",
	"rustdesk/rustdesk",

	// Editors & language servers
	"microsoft/vscode",
	"neovim/neovim",
	"zed-industries/zed",
	"helix-editor/helix",
	"lapce/lapce",
	"rust-lang/rust-analyzer",
	"sveltejs/language-tools",
	"alacritty/alacritty",
	"wezterm/wezterm",
	"zellij-org/zellij",
	"starship/starship",
	"atuinsh/atuin",

	// CLI & TUI tools
	"sharkdp/bat",
	"sharkdp/fd",
	"sharkdp/hyperfine",
	"BurntSushi/ripgrep",
	"eza-community/eza",
	"ClementTsang/bottom",
	"dandavison/delta",
	"jesseduffield/lazygit",
	"ajeetdsouza/zoxide",
	"junegunn/fzf",
	"charmbracelet/bubbletea",
	"charmbracelet/glow",
	"charmbracelet/gum",
	"charmbracelet/lipgloss",
	"spf13/cobra",
	"spf13/viper",
	"urfave/cli",
	"clap-rs/clap",
	"yt-dlp/yt-dlp",

	// CMS, commerce & backend platforms
	"strapi/strapi",
	"directus/directus",
	"payloadcms/payload",
	"keystonejs/keystone",
	"medusajs/medusa",
	"vendurehq/vendure",
	"saleor/saleor",
	"appwrite/appwrite",
	"supabase/supabase",

	// Low-code & workflow automation
	"n8n-io/n8n",
	"ToolJet/ToolJet",
	"appsmithorg/appsmith",
	"Budibase/budibase",
	"nocodb/nocodb",
	"windmill-labs/windmill",
	"activepieces/activepieces",
	"huginn/huginn",

	// Docs & presentation
	"withastro/starlight",
	"facebook/docusaurus",
	"slidevjs/slidev",

	// Self-hosted apps & productivity
	"immich-app/immich",
	"paperless-ngx/paperless-ngx",
	"linkwarden/linkwarden",
	"karakeep-app/karakeep",
	"gethomepage/homepage",
	"glanceapp/glance",
	"home-assistant/core",
	"outline/outline",
	"toeverything/AFFiNE",
	"makeplane/plane",
	"calcom/cal.diy",
	"simplex-chat/simplex-chat",
	"bluesky-social/social-app",
	"binwiederhier/ntfy",
	"juanfont/headscale",

	// Learning resources & collections
	"freeCodeCamp/freeCodeCamp",
	"codecrafters-io/build-your-own-x",
	"public-apis/public-apis",
	"kamranahmedse/developer-roadmap",
] as const;
